#!/usr/bin/python2.7

import os
import subprocess
import sys

def chmod_samba_dir(directory, user, (dirperm, filperm)):
    print "Chowning and Chmodding '%s' to '%s'.." % (directory, user)
    output = subprocess.check_output(['chown', '-R', '%s:%s' % (user, user), directory])
    for root, dirnames, filenames in os.walk(directory):
        for dn in dirnames:
            os.chmod(os.path.join(root, dn), dirperm)
        for fn in filenames:
            os.chmod(os.path.join(root, fn), filperm)
    print "Done."

# load up environment variables
try:
    SMB_PUB_SHARE = os.environ['SMB_PUB_SHARE']
    SMB_PUB_USR = os.environ['SMB_PUB_USR']
    SMB_PUB_PWD = os.environ['SMB_PUB_PWD']
    SMB_PUB_UID = os.environ['SMB_PUB_UID']
    SMB_PRV_SHARE = os.environ['SMB_PRV_SHARE']
    SMB_PRV_USR = os.environ['SMB_PRV_USR']
    SMB_PRV_PWD = os.environ['SMB_PRV_PWD']
    SMB_PRV_UID = os.environ['SMB_PRV_UID']
except KeyError as e:
    print >> sys.stderr, "Missing environment variable " + e.message
    sys.exit(1)

try:
    SMB_PUB_UID = int(SMB_PUB_UID)
    SMB_PRV_UID = int(SMB_PRV_UID)
except (AssertionError, ValueError) as e:
    print >> sys.stderr, "Bad environment variable " + e.message
    sys.exit(1)

# first the public user and dir
print "creating user", SMB_PUB_USR, SMB_PUB_UID
subprocess.check_call(['adduser', '-D', '-u', str(SMB_PUB_UID), '-s', '/bin/false', SMB_PUB_USR])
print "changing password.."
subprocess.check_call('echo "%s:$(echo %s | mkpasswd)" | chpasswd' % (SMB_PUB_USR, SMB_PUB_PWD), shell=True)
chmod_samba_dir('/samba/public', SMB_PUB_USR, (0755, 0644))

# now the private one
print "creating user", SMB_PRV_USR, SMB_PRV_UID
subprocess.check_call(['adduser', '-D', '-u', str(SMB_PRV_UID), '-s', '/bin/false', SMB_PRV_USR])
print "changing password.."
subprocess.check_call('echo "%s:$(echo %s | mkpasswd)" | chpasswd' % (SMB_PRV_USR, SMB_PRV_PWD), shell=True)
chmod_samba_dir('/samba/private', SMB_PRV_USR, (0750, 0640))

# now edit smb.conf
with open('/etc/samba/smb.conf', 'r') as f:
    content = f.read()
content = content.replace('XXpublicdirXX', SMB_PUB_SHARE)
content = content.replace('XXprivatedirXX', SMB_PRV_SHARE)
content = content.replace('XXsambapublicXX', SMB_PUB_USR)
content = content.replace('XXsambaprivateXX', SMB_PRV_USR)
print "writing smb conf:"
print content
print
with open('/etc/samba/smb.conf', 'w') as f:
    f.write(content)
