#!/usr/bin/python2.7

import os
import subprocess
import sys


def log(message, *args):
    print "{} : {}".format(__file__, message.format(*args))

def halt(message):
    log("ERROR {}", message)
    sys.exit(1)

def change_samba_password(user, password):
    log("Changing Samba password for user '{}'", user)
    proc = subprocess.Popen(['pdbedit', '-a', '-u', user], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    proc.stdin.write(password)
    proc.stdin.write('\n')
    proc.stdin.write(password)
    proc.stdin.write('\n')
    proc.stdin.flush()
    stdout,stderr = proc.communicate()
    print stdout
    if proc.wait():
        raise RuntimeError(proc)

if __name__ == '__main__':

    if 'SMB_PUB_PWD' not in os.environ:
        halt("Could not find SMB_PUB_PWD envvar")
    if 'SMB_PRV_PWD' not in os.environ:
        halt("Could not find SMB_PUB_PWD envvar")

    if os.environ['SMB_PUB_PWD'] == 'changeme':
        halt("SMB_PUB_PWD value was 'changeme' it must be changed!\n"
             "Please specify '-e SMB_PUB_PWD=xxxxx' when launching the container.")

    if os.environ['SMB_PRV_PWD'] == 'changeme':
        halt("SMB_PRV_PWD value was 'changeme' it must be changed!\n"
             "Please specify '-e SMB_PRV_PWD=xxxxx' when launching the container.")

    if 'SMB_PUB_USR' not in os.environ:
        halt("Could not find SMB_PUB_USR envvar")
    if 'SMB_PRV_USR' not in os.environ:
        halt("Could not find SMB_PRV_USR envvar")

    change_samba_password('sambapublic', os.environ['SMB_PUB_PWD'])
    change_samba_password('sambaprivate', os.environ['SMB_PRV_PWD'])
