#!/usr/bin/python2.7

import re
import os
import subprocess
import sys


def log(message, *args):
    print "{} : {}".format(__file__, message.format(*args))

def halt(message):
    log("ERROR {}", message)
    sys.exit(1)


if __name__ == '__main__':

    if 'SELF_ADDRESS' not in os.environ:
        halt("Could not find SELF_ADDRESS envvar.\n"
             "Please specify '-e SELF_ADDRESS=xxxx' as as ip address or hostname")

    self_address = os.environ['SELF_ADDRESS']
    log("SELF_ADDRESS = {}", self_address)

    with open('/srv/http/index.html', 'r') as f:
        index_html_before = f.read()

    index_html_after = index_html_before.replace('localhost', self_address)

    with open('/srv/http/index.html', 'w') as f:
        f.write(index_html_after)

    log("done")
