#!/usr/bin/python2.7

import json
import os
import shutil
import subprocess
import time


SETTINGS_DIR = '/home/debian-transmission'
SETTINGS_FILE = os.path.join(SETTINGS_DIR, 'settings.json')

if __name__ == '__main__':

    print __file__, ':', 'injecting port/password config'

    # backup settings file
    new_file_name = SETTINGS_FILE + '.%d' % time.time()
    shutil.copyfile(SETTINGS_FILE, new_file_name)

    with open(SETTINGS_FILE, 'r') as f:
        current_settings = json.loads(f.read())

    if 'WEBUI_PORT' in os.environ and os.environ['WEBUI_PORT']:
        current_settings['rpc-port'] = int(os.environ['WEBUI_PORT'])

    if 'WEBUI_PASSWORD' in os.environ and os.environ['WEBUI_PASSWORD']:
        assert (os.environ['WEBUI_PORT'] != 'changeme')
        current_settings['rpc-password'] = os.environ['WEBUI_PASSWORD'].strip()

    with open(SETTINGS_FILE, 'w') as f:
        f.write(json.dumps(current_settings))

    print __file__, ':', 'done'
