#!/usr/bin/python2.7

import json
import os
import shutil
import sys
import subprocess
import time


SUPERVISORD_CONF = '/etc/supervisor/conf.d/supervisord.conf'

def chmod_dir(directory, user, (dirperm, filperm)):
    print "Chowning and Chmodding '%s' to '%s'.." % (directory, user)
    output = subprocess.check_output(['chown', '-R', '%s:%s' % (user, user), directory])
    for root, dirnames, filenames in os.walk(directory):
        for dn in dirnames:
            os.chmod(os.path.join(root, dn), dirperm)
        for fn in filenames:
            os.chmod(os.path.join(root, fn), filperm)
    print "Done."

def log(message, *args):
    print "{} : {}".format(__file__, message.format(*args))

def halt(message):
    log("ERROR {}", message)
    sys.exit(1)

def load_nordvpns():
    files = os.listdir('/nordvpn')
    files = [f for f in files if os.path.isfile(os.path.join('/nordvpn', f))]
    return files

if __name__ == '__main__':

    # load up environment variables
    try:
        DOWNLOADER_USR = os.environ['DOWNLOADER_USR']
        DOWNLOADER_UID = os.environ['DOWNLOADER_UID']
    except KeyError as e:
        print >> sys.stderr, "Missing environment variable " + e.message
        sys.exit(1)

    try:
        VPN_USER, VPN_PASS = os.environ['NORDVPN_CRED'].split('|', 1)
        with open('/vpnauth.dat', 'w') as f:
            f.write("%s\n" % VPN_USER)
            f.write("%s\n" % VPN_PASS)
        NORDVPN_FILE = os.environ['NORDVPN_FILE']

        vpns = load_nordvpns()
        if NORDVPN_FILE not in vpns:
            print >> sys.stderr, "Vpn file '%s' is not one of the allowed values. Pick from %s" % (
                NORDVPN_FILE,
                ', '.join(vpns)
            )
            sys.exit(1)

    except KeyError as e:
        print >> sys.stderr, "Missing environment variable " + e.message
        sys.exit(1)


    try:
        DOWNLOADER_UID = int(DOWNLOADER_UID)
    except (AssertionError, ValueError) as e:
        print >> sys.stderr, "Bad environment variable " + e.message
        sys.exit(1)

    with open('/etc/resolv.conf', 'w') as f:
        f.write("search local\nnameserver 162.242.211.137\nnameserver 78.46.223.24\n")

    # first the public user and dir
    print "creating user", DOWNLOADER_USR, DOWNLOADER_UID
    subprocess.check_call(['adduser', '-D', '-u', str(DOWNLOADER_UID), '-s', '/bin/false', DOWNLOADER_USR])

    # create and chmod dirs

    chmod_dir('/t/downloads', DOWNLOADER_USR, (0755, 0644))
    chmod_dir('/t/incomplete', DOWNLOADER_USR, (0755, 0644))
    chmod_dir("/etc/transmission-daemon", DOWNLOADER_USR, (0755, 0644))

    log("Injecting user into supervisord config")

    with open(SUPERVISORD_CONF, 'r') as f:
        content = f.read()
    content = content.replace('%injectuser%', DOWNLOADER_USR)
    content = content.replace('%vpnfile%', os.path.join('/nordvpn', NORDVPN_FILE))
    with open(SUPERVISORD_CONF, 'w') as f:
        f.write(content)

    log('done')
